# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170325_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
